chore(cicd): add semantic-release to build pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,12 +7,25 @@ on:
 
   workflow_dispatch:
 
+permissions:
+  contents: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+          persist-credentials: false
+
+      - name: Set Up Git Identity
+        run: |
+          git config --global user.email "$(git log -1 --pretty=format:'%ae' | xargs)"
+          git config --global user.name "$(git log -1 --pretty=format:'%an' | xargs)"
+          git remote set-url origin "https://${{ github.actor }}:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}"
 
       - name: Set up Python
         uses: actions/setup-python@v3
@@ -23,6 +36,25 @@ jobs:
         run: |
           pip install pipx==1.2.1
 
+      - name: Update Version and Changelog
+        run: |
+          pipx install python-semantic-release==8.3.0
+          semantic-release -v version --no-vcs-release --no-commit
+          differences=$(git diff | xargs)
+
+          if [ -z "$differences" ]; then
+            exit 0
+          fi
+
+          git add --all
+          git commit -m "chore(release): bump version and update changelog"
+          git push
+
+          echo "::error::There is a diff in the files"
+          echo "$differences"
+          exit 1
+          
+
       - name: Build package
         run: |
           pipx run build
@@ -32,3 +64,9 @@ jobs:
         with:
           user: __token__
           password: ${{ secrets.PYPI_API_TOKEN }}
+        
+      - name: Create Git Tag
+        run: |
+          version_number=$(semantic-release -v version --print)
+          git tag $version_number
+          git push origin --tags
