feat(cicd): combine check and test pipelines

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,12 +1,19 @@
 name: Test
 
 on:
-  workflow_run:
-    workflows: Check
-    types: completed
+  push:
+    branches:
+      - "master"
+
+  pull_request:
+    branches:
+      - "master"
+
+  workflow_dispatch:
 
 permissions:
   actions: read
+  contents: write
   pull-requests: write
   checks: write
 
@@ -15,9 +22,61 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  check_changelog:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          persist-credentials: false
+
+      - name: Set Up Git Identity
+        run: |
+          git fetch -v -v -v --all --unshallow
+          git switch "${{ github.REF_NAME }}" || git switch "${{ github.HEAD_REF }}"
+          git config --global user.email "$(git log -1 --pretty=format:'%ae' | xargs)"
+          git config --global user.name "${{ github.actor }}"
+          git remote set-url origin "https://${{ github.actor }}:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}"
+
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.8"
+
+      - name: Install dependencies
+        run: |
+          pip install pipx==1.2.1 pipenv==2023.2.4
+
+      - name: Update Version and Changelog
+        run: |
+          pipx install python-semantic-release==8.3.0
+          semantic-release -v version --no-vcs-release --no-commit
+          differences=$(git diff | xargs)
+
+          if [ -z "$differences" ]; then
+            echo "No changes needed"
+            exit 0
+          fi
+
+          echo "Version and/or Changelog needs to be updated"
+
+          git add --all
+          git commit -m "chore(release): bump version and update changelog"
+          git push
+
+          echo "::error::The version and/or Changelog is outdated"
+          echo "$differences"
+          sleep 30
+          exit 1
+
+      - name: Check Breaking changes
+        run: |
+          package_version=$(semantic-release -v version --print)
+          pipenv install --dev --deploy
+          pipx install .
+          pycracks -vv -t $package_version
   test:
     runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
 
     strategy:
       matrix:
@@ -56,7 +115,9 @@ jobs:
 
   test-finish:
     needs: test
+
     if: always()
+
     runs-on: ubuntu-latest
 
     steps:
